language: python
cache: pip

python:
  - "2.7"

install: 
  - pip install -r requirements.txt

script:
  - travis_wait 30 sphinx-build -a -j8 . _build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _build/html/
  on:
    branch: gh-pages