language: python
cache: pip

python:
  - "2.7"

install: 
  - pip install -r requirements.txt

script:
  - sphinx-build -a -j4 . _build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master